@os_base_url=http://localhost:9200

### ADMIN

### Get indices info
GET {{os_base_url}}/_cat/indices

### Get Plugin info
GET {{os_base_url}}/_cat/plugins?v=true&pretty

### Opensearch Queries

### Search for title
GET {{os_base_url}}/tmdb/_search
Content-Type: application/json

{
    "query": {
        "match": {
            "title": "First"
        }
    }
}

### LTR - Initialise default feature store
PUT {{os_base_url}}/_ltr

### LTR - List all features in the featureset
GET {{os_base_url}}/_ltr/_featureset

### Delete default feature store
DELETE {{os_base_url}}/_ltr

### LTR Feature Logging - SLTR Query
GET {{os_base_url}}/tmdb/_search
Content-Type: application/json

{
    "query": {
        "bool": {
            "must": { 
                "match": {
                    "title": "First"
                }
            },
            "filter" : [
                {
                    "sltr" : {
                        "featureset" : "moviefeatureset",
                        "_name": "logged_featureset",
                        "active_features" : [ 
                            "title_query",
                            "overview_query"
                        ],
                        "params": {
                            "query_text": "First"
                        }
                    }
                }
            ]
        }
    },
    "ext": {
        "ltr_log": {
            "log_specs": {
                "name": "log_entry1",
                "named_query": "logged_featureset"
            }
        }
    }
}

### LTR Feature Logging - SLTR Query with profiling
GET {{os_base_url}}/tmdb/_search
Content-Type: application/json

{
    "profile": true,  
    "query": {
        "bool": {
            "must": { 
                "match": {
                    "title": "First"
                }
            },
            "filter" : [
                {
                    "sltr" : {
                        "featureset" : "moviefeatureset",
                        "_name": "logged_featureset",
                        "active_features" : [ 
                            "title_query",
                            "overview_query"
                        ],
                        "params": {
                            "query_text": "First"
                        }
                    }
                }
            ]
        }
    },
    "ext": {
        "ltr_log": {
            "log_specs": {
                "name": "log_entry1",
                "named_query": "logged_featureset"
            }
        }
    }
}


### LTR Feature Logging - SLTR Query with rescore
GET {{os_base_url}}/tmdb/_search
Content-Type: application/json

{
    "profile": true,  
    "query": {
        "match": {
            "title": "First"
        }
    },
    "rescore": {
        "window_size": 1000,
        "query": {
            "rescore_query": {
                "sltr" : {
                    "featureset" : "moviefeatureset",
                    "_name": "logged_featureset",
                    "active_features" : [ 
                        "title_query",
                        "overview_query"
                    ],
                    "params": {
                        "query_text": "First"
                    }
                }
            }
        }
    },
    "ext": {
        "ltr_log": {
            "log_specs": {
                "name": "log_entry1",
                "named_query": "logged_featureset"
            }
        }
    }
}

### GET LTR Stats
# https://github.com/o19s/elasticsearch-learning-to-rank/pull/308
GET {{os_base_url}}/_ltr/_stats
